### ISSUE TITLE
Error restoring session when switching from a restored session

### ISSUE THREAD

**Issue by jacktuck** [rmagatti/session-lens#43] opened 2023-08-16 18:32 UTC
Firstly, thank you for your work on auto-session and session-lens!

I've come across the following issue.. I'm probably doing something wrong ?

(I have a session for dirA and dirB. I've tried deleting the sessions and starting again but always get this error)

The following works fine
```
cd dirA
nvim .
:Telescope session-lens search_session
<select dirB>
```
and without session-lens is also fine
```
cd dirB
nvim
```

However If I do
```
cd dirA
nvim
:Telescope session-lens search_session
<select dirB>
```
(get the same error if i source the session)

I get the following
```
auto-session ERROR: Error restoring session! The session might be corrupted.
Disabling auto save. Please check for errors in your config. Error:
Press ENTER or type command to continue
Vim(unlet):E108: No such variable: "SessionLoad"
```

**Comment by jacktuck** [comment] 2023-08-16 18:32
❯ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by jacktuck** [comment] 2023-08-16 19:10
If I remove auto-session and source the sessions I have no problem

**Comment by rmagatti** [comment] 2023-08-16 19:40
Duplicate of this one?
https://github.com/rmagatti/session-lens/issues/35

I think this was an issue upstream, you might want to upgrade to the latest neovim version and try again.
Also, this project will be sunset soon 🌆 as session-lens functionality has been fully merged into auto-session. https://github.com/rmagatti/auto-session/pull/161

**Closed** 2023-08-17 10:03 UTC
